export default [
    {
        files: ['modules/esm/**/*.mjs'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                AbortController: 'readonly',
                addEventListener: 'readonly',
                atob: 'readonly',
                Blob: 'readonly',
                caches: 'readonly',
                cancelAnimationFrame: 'readonly',
                clearInterval: 'readonly',
                clearTimeout: 'readonly',
                console: 'readonly',
                createImageBitmap: 'readonly',
                CustomEvent: 'readonly',
                document: 'readonly',
                Element: 'readonly',
                Event: 'readonly',
                fetch: 'readonly',
                File: 'readonly',
                FormData: 'readonly',
                getComputedStyle: 'readonly',
                globalThis: 'readonly',
                history: 'readonly',
                Image: 'readonly',
                innerHeight: 'readonly',
                innerWidth: 'readonly',
                localStorage: 'readonly',
                location: 'readonly',
                matchMedia: 'readonly',
                MediaRecorder: 'readonly',
                MutationObserver: 'readonly',
                navigator: 'readonly',
                Node: 'readonly',
                NodeFilter: 'readonly',
                Notification: 'readonly',
                OffscreenCanvas: 'readonly',
                Path2D: 'readonly',
                performance: 'readonly',
                queueMicrotask: 'readonly',
                requestAnimationFrame: 'readonly',
                ResizeObserver: 'readonly',
                Response: 'readonly',
                sessionStorage: 'readonly',
                setInterval: 'readonly',
                setTimeout: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly'
            }
        },
        linterOptions: { reportUnusedDisableDirectives: 'error' },
        rules: {
            'eqeqeq': ['error', 'always', { null: 'ignore' }],
            'no-eval': 'error',
            'no-new-func': 'error',
            'no-implied-eval': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'no-undef': 'error',
            'no-unreachable': 'error',
            'no-duplicate-imports': 'error'
        }
    }
];
