#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
if [ -f .env ]; then
  echo '.env esiste già: non lo sovrascrivo.'
  exit 0
fi
umask 077
APP_PASS="$(openssl rand -hex 24)"
ROOT_PASS="$(openssl rand -hex 32)"
cat > .env <<EOF_ENV
MYSQL_DATABASE=meteonexa
MYSQL_USER=meteonexa
MYSQL_PASSWORD=${APP_PASS}
MYSQL_ROOT_PASSWORD=${ROOT_PASS}
METEONEXA_BASE_URL=https://www.meteonexa.com/
METEONEXA_DB_CONTAINER_NAME=meteonexa-db
METEONEXA_WEB_CONTAINER_NAME=meteonexa-web
METEONEXA_WORKER_CONTAINER_NAME=meteonexa-worker
METEONEXA_RUNTIME_DIR=./runtime
METEONEXA_WORKER_INTERVAL_SECONDS=180
METEONEXA_SMTP_HOST=smtp-relay.brevo.com
METEONEXA_SMTP_PORT=587
METEONEXA_SMTP_ENCRYPTION=tls
METEONEXA_SMTP_USERNAME=
METEONEXA_SMTP_PASSWORD=
METEONEXA_SMTP_FROM_EMAIL=alerts@meteonexa.com
METEONEXA_SMTP_FROM_NAME=MeteoNexa
METEONEXA_SMTP_TIMEOUT_SECONDS=18
METEONEXA_PRIVACY_CONTACT_EMAIL=
METEONEXA_LEGAL_CONTROLLER_NAME=
METEONEXA_LEGAL_CONTROLLER_ADDRESS=
METEONEXA_DPO_EMAIL=
METEONEXA_LEGAL_SITE_URL=https://www.meteonexa.com/
METEONEXA_XWEATHER_CLIENT_ID=
METEONEXA_XWEATHER_CLIENT_SECRET=
METEONEXA_METEOALARM_EDR_TOKEN=
METEONEXA_SYNOP_OBSERVATION_URL=
METEONEXA_ARPA_OBSERVATION_URL=
METEONEXA_RADAR_FALLBACK_METADATA_URL=
METEONEXA_RADAR_ALLOWED_HOSTS=
METEONEXA_RADAR_TILE_GLOBAL_HOUR=30000
EOF_ENV
chmod 600 .env
echo '.env creato con credenziali MySQL casuali. Non condividerlo e non committarlo.'
